### PR TITLE
Issue 7 update makefile

### PR DESCRIPTION
**Pull request by zendril**
PR for #7 to expand the build capabilities.

Includes 
- vendoring
- tidy
- fmt
- test (with coverage)
- ci (does the test & build)
- github actions update to use `make ci`

### CODE REVIEW

**Comment by neilpa** [comment]
I'm not so sure about this change. This breaks a couple of key things that the current simple `Makefile` does. That is, embedding the version number in the pre-built binaries, creating them in the `build/` directory, and with the proper naming scheme for platform/arch so that they don't overwrite each other.

There are also some things that I'd prefer not to do locally like running code coverage by default on tests or having `-v` included on everything. I don't mind these on CI builds but for local iterations I prefer the "less is more" style the of standard go tooling.

**Comment by zendril** [comment]
As always, its just a starting point. :)

+1 for version number
+1 I'm also a fan of putting things into build/ so I'll make sure they go there.. I don't like things littering the base or src dirs.

I would propose instead of naming the files themselves with the arch in the filename, instead having them land in subdirs for those archs. That way, when you publish and download, you don't have to rename somthing like to just yajsv. OR, perhaps a better alternative is to package them in os/arch specific tar.gz and zip files and inside of that is the LICENSE, README and the binary that is the short name.  Thoughts?

Maybe we can focus on the above first and then discuss the coverage and -v?

**Comment by zendril** [comment]
Check the latest.. 

- added version back in
- started work to make the version also print out the git commit and buildteimestamp
- moved the built assets into a structure like so:
```
bin
|-- darwin-amd64
|               `-- yajsv
|-- linux-amd64
|               `-- yajsv
`-- windows-amd64
                `-- yajsv.exe
```
- added clean makefile target

**Comment by zendril** [comment]
@neilpa Done for the night. I see you are doing some refactoring on the tests. I'll pull in the morning and look for any feedback. Cheers.

**Comment by neilpa** [comment]
> moved the built assets into a structure like so:

I want to keep the flat structure of the currently named binaries. Especially since GitHub releases only support files and no directory structure. I also don't see the value in wrapping them in a tarball or zip file since that's still another step when downloading. Might as well just rename the file to whatever you want to call it.

> started work to make the version also print out the git commit and buildteimestamp

I actually experimented a fair bit with this until I settled on the current `git describe` output. I'd like to keep this as-is for now w/out the commit or timestamp in the pre-built binaries. If you're not an explicit tag the commit will already be appended. As for the timestamp, I'd rather not add that.

My preference for the other changes would be to tackle each as a small PR, one at a time. Right now the build is very simple, not much different than a stock `go build`. I'd like for that to continue rather than the wholesale rewrite that this change currently is.

**Comment by zendril** [comment]
Fair enough. It's your baby and it was a good learning experience. 

If there are specific other parts you would like to bring in, let me know and I'll break it into smaller PR.

Want me to just close this PR?

**Comment by neilpa** [comment]
Having the `fmt`, `tidy`, `ci` and a new `cover` target for code-coverage are all good to have in there. Would be better as a new PR though and close this one out

**Comment by neilpa** [comment]
> it was a good learning experience.

Also, that's good to hear.

**Comment by zendril** [comment]
> Having the `fmt`, `tidy`, `ci` and a new `cover` target for code-coverage are all good to have in there. Would be better as a new PR though and close this one out

Sounds like a plan.

Btw, like what I saw so far with the test refactoring.. I was only looking on my phone so hard to really get the context.. but looked much better.

**Comment by neilpa** [comment]
> Btw, like what I saw so far with the test refactoring.. I was only looking on my phone so hard to really get the context.. but looked much better.

I'm not sure how familiar you are with different styles of go tests but there's a [good link on the go wiki](https://github.com/golang/go/wiki/TableDrivenTests) about the pattern I switched over to.

**Pull request closed without merging**
